### ISSUE TITLE
Indent error on generated views plugin

### ISSUE THREAD

**Issue by jepster** [hechoendrupal/DrupalConsole#2943] opened 2016-11-14 20:57 UTC
I have generated a views plugin:

```
peter@computer ~/Websites/pbt-d8 $ drupal generate:plugin:type:yaml

 // Welcome to the Drupal Plugin Type generator
 Enter the module name [devel]:
 > permissions_by_term

 Plugin type class name [ExamplePlugin]:
 > ViewsFilterPlugin

 Plugin type machine name [views_filter_plugin]:
 > 

 Plugin file name [views.filter.plugin]:
 > 

Generated or updated files

 1 - modules/permissions_by_term/src/ViewsFilterPluginManager.php
 2 - modules/permissions_by_term/src/ViewsFilterPluginManagerInterface.php
 3 - modules/permissions_by_term/permissions_by_term.services.yml
 4 - modules/permissions_by_term/permissions_by_term.views.filter.plugin.yml
peter@computer ~/Websites/pbt-d8 
```
Afterwards I got this error:

> [Mon Nov 14 21:52:59.407229 2016] [:error] [pid 3338] [client 127.0.0.1:55124] Drupal\\Component\\Serialization\\Exception\\InvalidDataTypeException: Indentation problem at line 13 (near "  plugin.manager.views_filter_plugin:"). in /home/peter/Websites/pbt-d8/core/lib/Drupal/Component/Serialization/YamlSymfony.php on line 39 #0 /home/peter/Websites/pbt-d8/core/lib/Drupal/Component/Serialization/Yaml.php(35): Drupal\\Component\\Serialization\\YamlSymfony::decode('services:\\n    p...')\n#1 /home/peter/Websites/pbt-d8/core/lib/Drupal/Core/DependencyInjection/YamlFileLoader.php(343): Drupal\\Component\\Serialization\\Yaml::decode('services:\\n    p...')\n#2 /home/peter/Websites/pbt-d8/core/lib/Drupal/Core/DependencyInjection/YamlFileLoader.php(63): Drupal\\Core\\DependencyInjection\\YamlFileLoader->loadFile('modules/permiss...')\n#3 /home/peter/Websites/pbt-d8/core/lib/Drupal/Core/DrupalKernel.php(1224): Drupal\\Core\\DependencyInjection\\YamlFileLoader->load('modules/permiss...')\n#4 /home/peter/Websites/pbt-d8/core/lib/Drupal/Core/DrupalKernel.php(866): Drupal\\Core\\DrupalKernel->compileContainer()\n#5 /home/peter/Websites/pbt-d8/core/lib/Drupal/Core/DrupalKernel.php(461): Drupal\\Core\\DrupalKernel->initializeContainer()\n#6 /home/peter/Websites/pbt-d8/core/lib/Drupal/Core/DrupalKernel.php(651): Drupal\\Core\\DrupalKernel->boot()\n#7 /home/peter/Websites/pbt-d8/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#8 {main}

The indent which has been added to

> modules/permissions_by_term/permissions_by_term.services.yml

has been wrong. I have fixed it manually. The needed indent has been 4 spaces. Not 2.

**Comment by enzolutions** [comment] 2016-11-16 19:17
Hi @jepster 

Thank you for your report, I tried to reproduce the error mentioned, but all works as expected, this is what I did

```bash 
$drupal generate:module  --module="Permissions by term" --machine-name="permissions_by_term" --module-path="/modules/custom" --description="My Awesome Module" --core="8.x" --package="Custom" --module-file --composer --test 

$ drupal generate:plugin:type:yaml  --module="permissions_by_term" --class="ViewsFilterPlugin" --plugin-name="views_filter_plugin" --plugin-file-name="views.filter.plugin" 

$ drupal module:install permissions_by_term

$ drupal cache:rebuild  all
```

This is the content of file permissions_by_term.services.yml

```
services:
  plugin.manager.views_filter_plugin:
    class: Drupal\permissions_by_term\ViewsFilterPluginManager
    arguments: ['@module_handler', '@cache.discovery']
```

Could you, provide more information about how and where do you get this error?

Meanwhile I will if is required 4 spaces indentation.

**Comment by jmolivas** [comment] 2016-12-23 02:50
@jepster closing this since looks like works as expected feel free to re-open if issue still happening after updating to latest version of DrupalConsole.

**Closed by jmolivas** 2016-12-23 02:50 UTC
Labels: needs-review
