### ISSUE TITLE
After generating a new entity ..routing.yml does not exist 

### ISSUE THREAD

**Issue by maen007** [hechoendrupal/DrupalConsole#1799] opened 2016-01-26 08:36 UTC
I had to create it manually...

**Comment by jmolivas** [comment] 2016-01-26 17:11
May you include steps related how to reproduce:

**Details to include:**
- Drupal version (you can obtain this by running `drupal site:status`).  
- Console version (you can obtain this by running `drupal --version`).
- Steps to reproduce
  * Executed command.
  * Ouput messages
  * Include screen-shot or video whenever necessary.

**Comment by maen007** [comment] 2016-01-27 06:27
Drupal 8.0.1 
PHP: 5.5.9
Drupal Console version 0.10.5
OS: ubuntu 14.04
Executed commands: 
- drupal generate:module
- drupal generate:entity:content

**Comment by HaleFx** [comment] 2016-01-28 15:55
I noticed this change a few versions back. It isn't needed. The defined handlers and EntityHtmlRouteProvider.php seem to take care of everything.

**Comment by maen007** [comment] 2016-01-28 16:59
Nope, after usind the commands and trying to open the settings, there comes a fatal error. So the settings are not routed. Thus I created the routing.yml by hand.

**Comment by HaleFx** [comment] 2016-01-28 17:02
The settings path doesn't work because of #1726

**Comment by jmolivas** [comment] 2016-02-01 06:45
Fixed with PR https://github.com/hechoendrupal/DrupalConsole/pull/1805

**Closed by jmolivas** 2016-02-01 06:45 UTC
Labels: need-more-information
