### ISSUE TITLE
[any command], is not a valid command name.

### ISSUE THREAD

**Issue by vacho** [hechoendrupal/DrupalConsole#2962] opened 2016-11-17 18:36 UTC
First. The commands were working fine.
After a while they all started to fail. None works.

Example:
[ERROR] Command "cr", is not a valid command name.
[ERROR] Command "route:rebuild", is not a valid command name. 
...

Version:
Drupal Console (1.0.0-rc9)
Ubuntu 16.04
Php 7
Drupal 8.2.3

**Comment by jmolivas** [comment] 2016-11-18 02:07
@vacho can you see if any error files logged at `site/console/log` ?

**Comment by vacho** [comment] 2016-11-21 12:20
@jmolivas I can't find this path

**Comment by jmolivas** [comment] 2016-11-21 17:15
@vacho can you look into your php system error log files?

**Comment by vacho** [comment] 2016-11-21 19:01
OK, 
at /var/log/apache2/error.log doesn't apeear anything.

I have detected that this is starting to happen after enabling certain modules in my project. It is very strange, this did not happen before upgrading the version.

**Comment by jmolivas** [comment] 2016-11-22 05:55
@vacho can you share which modules are causing this?

**Comment by littlethoughts** [comment] 2016-12-05 15:57
Same here, I also checked in my error logs but couldn't see anything.
I was using the global phar installation first, but removed it to make sure there are no mix-ups. I installed it in the project with composer after that.

Versions:
drupal/console 1.0.0-rc10
Drupal 8.1.10
PHP 7.0.7
Mac OS X El Capitan

**Comment by jmolivas** [comment] 2016-12-05 16:04
@littlethoughts is your drupal installer?

try executing the `site:install` command

**Comment by jmolivas** [comment] 2016-12-05 16:04
@vacho @littlethoughts you can always try the `list` command to see the available commands.

**Comment by littlethoughts** [comment] 2016-12-05 16:14
@jmolivas thank you for your fast response (as always). I was being too fast with thinking there is an issue, my database wasn't running because of an update I had done earlier.

**Comment by vacho** [comment] 2016-12-13 18:04
I solve my problem. 

At some place of my code, had this:
\Drupal::configFactory()->getEditable('system.site')
    ->set('page.404', 'not-found')
    ->save();

I replace it by this

\Drupal::configFactory()->getEditable('system.site')
    ->set('page.404', '/not-found')
    ->save();

And it solve!!

All comands of drupal console fail when some code fail and doesn't show any report why fail.

**Closed** 2016-12-18 00:41 UTC

**Comment by iBobik** [comment] 2019-02-25 13:32
@jmolivas Is it really expected behavior to not output correct error messages when something fails?
