### ISSUE TITLE
[LogicException] Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead.

### ISSUE THREAD

**Issue by OnkelTem** [hechoendrupal/DrupalConsole#1987] opened 2016-03-03 23:02 UTC
When I run `drupal` under a drupal site installation I get this message:

```
 [LogicException]                                                                                                                                                            
  Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead. 
```

A screenshot:

![](https://sc-cdn.scaleengine.net/i/d323cf1efec4baf2eb2df3044d986e67.png)

**Comment by darol100** [comment] 2016-03-06 17:27
@OnkelTem , This error message happens when Pathauto is installed. We need to investigate more about this issue.

**Comment by OnkelTem** [comment] 2016-03-06 18:06
I confirm the relation to Pathauto. After I uninstalled the module, the message is gone.

**Comment by chx** [comment] 2016-03-07 03:23
I don't have pathauto installed and yet I get this. Every time I try to use this, I am dissuaded again for weeks. Remind me why this wasn't merged back into drush mb? :(

**Comment by jmolivas** [comment] 2016-03-07 04:09
I saw this also with pathauto, which non-core modules you have installed @chx?

**Comment by chx** [comment] 2016-03-07 04:21
og, og_ui, flag are the bigger ones. A few custom ones but unlikely those cause problems (as they are not firing on likely hooks)

**Comment by jmolivas** [comment] 2016-03-07 04:22
how about your drupal version is 8.0.x, 8.1.x?

**Comment by chx** [comment] 2016-03-07 04:42
8.0.x for now

**Comment by OnkelTem** [comment] 2016-03-07 09:13
8.0.5 here

**Comment by chx** [comment] 2016-03-09 05:02
8.1.x too with nothing major from contrib (migrate_plus, migrate_tools and a very small custom)

**Comment by jmolivas** [comment] 2016-03-09 17:29
I am testing this on 8.0.5 and trace the error by executing: 
```
drupal --verbose
```
And I received this output log.

>  [LogicException]
  Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead.

```
Exception trace:
 () at /Users/jmolivas/develop/drupal/sites/drupal8.dev/core/lib/Drupal/Core/Render/Renderer.php:246
 Drupal\Core\Render\Renderer->doRender() at /Users/jmolivas/develop/drupal/sites/drupal8.dev/core/lib/Drupal/Core/Render/Renderer.php:200
 Drupal\Core\Render\Renderer->render() at /Users/jmolivas/develop/drupal/sites/drupal8.dev/core/modules/system/system.install:660
 system_requirements() at n/a:n/a
 call_user_func_array() at /Users/jmolivas/develop/drupal/sites/drupal8.dev/core/lib/Drupal/Core/Extension/ModuleHandler.php:393
 Drupal\Core\Extension\ModuleHandler->invokeAll() at /Users/jmolivas/develop/drupal/sites/drupal8.dev/core/modules/system/src/SystemManager.php:116
 Drupal\system\SystemManager->listRequirements() at /Users/jmolivas/develop/drupal/modules/console/src/Helper/SiteHelper.php:357
 Drupal\Console\Helper\SiteHelper->getDrupalVersion() at /Users/jmolivas/develop/drupal/modules/console/src/Command/AboutCommand.php:44
 Drupal\Console\Command\AboutCommand->execute() at /Users/jmolivas/develop/drupal/modules/console/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /Users/jmolivas/develop/drupal/modules/console/vendor/symfony/console/Application.php:849
 Symfony\Component\Console\Application->doRunCommand() at /Users/jmolivas/develop/drupal/modules/console/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /Users/jmolivas/develop/drupal/modules/console/src/Application.php:282
 Drupal\Console\Application->doRun() at /Users/jmolivas/develop/drupal/modules/console/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /Users/jmolivas/develop/drupal/modules/console/bin/drupal.php:97
 require() at /Users/jmolivas/develop/drupal/modules/console/bin/drupal:4
```

The excepetion is throw at: `core/lib/Drupal/Core/Render/Renderer.php` line 246 https://github.com/drupal/drupal/blob/8.0.5/core/lib/Drupal/Core/Render/Renderer.php#L246

I am showing code from line 244 - 248:
```
$context = $this->getCurrentRenderContext();
if (!isset($context)) {
  throw new \LogicException("Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead.");
}
```

**Comment by jmolivas** [comment] 2016-03-10 16:26
This error will go away on next release, `getDrupalVersion` was updated to: 
```
public function getDrupalVersion()
{
    return \Drupal::VERSION;
}
```

The error still happening on `site:status` when pathauto and probably other modules are loaded, I do still need to find what the changes are and how to avoid this error.

**Comment by jmolivas** [comment] 2016-03-10 16:27
Leave open until v0.10.13 release.

**Closed** 2016-03-21 07:37 UTC
Labels: bug

**Comment by nahueldotme** [comment] 2016-04-13 06:20
I'm having same issue here but with D 8.0.6
```
[LogicException]                                                                                                                                                        
  Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render inst  
  ead.                                                                                                                                                                    
                                                                                                                                                                          


Exception trace:
 () at /home/nahuel/public_html_nahuel.me/core/lib/Drupal/Core/Render/Renderer.php:246
 Drupal\Core\Render\Renderer->doRender() at /home/nahuel/public_html_nahuel.me/core/lib/Drupal/Core/Render/Renderer.php:200
 Drupal\Core\Render\Renderer->render() at /home/nahuel/public_html_nahuel.me/core/modules/system/system.install:660
 system_requirements() at n/a:n/a
 call_user_func_array() at /home/nahuel/public_html_nahuel.me/core/lib/Drupal/Core/Extension/ModuleHandler.php:393
 Drupal\Core\Extension\ModuleHandler->invokeAll() at /home/nahuel/public_html_nahuel.me/core/modules/system/src/SystemManager.php:116
 Drupal\system\SystemManager->listRequirements() at phar:///home/nahuel/public_html_nahuel.me/drupal.phar/src/Command/Site/StatusCommand.php:94
 Drupal\Console\Command\Site\StatusCommand->getSystemData() at phar:///home/nahuel/public_html_nahuel.me/drupal.phar/src/Command/Site/StatusCommand.php:64
 Drupal\Console\Command\Site\StatusCommand->execute() at phar:///home/nahuel/public_html_nahuel.me/drupal.phar/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///home/nahuel/public_html_nahuel.me/drupal.phar/vendor/symfony/console/Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/nahuel/public_html_nahuel.me/drupal.phar/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///home/nahuel/public_html_nahuel.me/drupal.phar/src/Application.php:282
 Drupal\Console\Application->doRun() at phar:///home/nahuel/public_html_nahuel.me/drupal.phar/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///home/nahuel/public_html_nahuel.me/drupal.phar/bin/drupal.php:97
 require() at phar:///home/nahuel/public_html_nahuel.me/drupal.phar/bin/drupal:3
 require() at /home/nahuel/public_html_nahuel.me/drupal.phar:10
```

**Comment by jmolivas** [comment] 2016-04-13 06:21
@nahueldotme Is this a D8 fresh install or there is any contrib modules on your project?

**Comment by nahueldotme** [comment] 2016-04-13 06:23
I do have contribs, including pathauto

**Comment by danielnv18** [comment] 2016-04-18 05:24
I got that message when I run ```drupal site:status```
I have Drupal Console version 0.11.3, Drupal 8.0.5 and some contrib including pathauto

**Comment by dhendriks** [comment] 2018-02-11 12:17
The issue is closed, but it seems it is still present. I have it for Drupal 8.4.4 with Drush Commandline Tool 9.0.0. I have pathauto installed. I get the problem not for site:status, but for twig:compile.

[error]  Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead.

**Comment by jmolivas** [comment] 2018-02-11 17:39
@dhendriks could you mention the steps you have to do to replicate it.

**Comment by dhendriks** [comment] 2018-02-12 14:00
```
$ drush9 twig:compile
 [success] Compiled twig template modules/addtoany/templates/addtoany-standard.html.twig
 [success] Compiled twig template core/modules/block/templates/block.html.twig
 [success] Compiled twig template core/modules/block_content/templates/block-content-add-list.html.twig
 [success] Compiled twig template modules/captcha/templates/captcha.html.twig
 [success] Compiled twig template core/modules/ckeditor/templates/ckeditor-settings-toolbar.html.twig
 [success] Compiled twig template core/modules/color/templates/color-scheme-form.html.twig
 [success] Compiled twig template core/modules/comment/templates/comment.html.twig
 [success] Compiled twig template core/modules/comment/templates/field--comment.html.twig
 [success] Compiled twig template core/modules/config_translation/templates/config_translation_manage_form_element.html.twig
 [success] Compiled twig template modules/ctools/templates/ctools-wizard-trail-links.html.twig
 [success] Compiled twig template modules/ctools/templates/ctools-wizard-trail.html.twig
 [success] Compiled twig template core/modules/field_ui/templates/field-ui-table.html.twig
 [success] Compiled twig template core/modules/file/templates/file-upload-help.html.twig
 [success] Compiled twig template core/modules/file/templates/file-link.html.twig
 [success] Compiled twig template core/modules/file/templates/file-managed-file.html.twig
 [success] Compiled twig template core/modules/file/templates/file-widget-multiple.html.twig
 [success] Compiled twig template core/modules/filter/templates/text-format-wrapper.html.twig
 [success] Compiled twig template core/modules/filter/templates/filter-guidelines.html.twig
 [success] Compiled twig template core/modules/filter/templates/filter-tips.html.twig
 [success] Compiled twig template core/modules/filter/templates/filter-caption.html.twig
 [success] Compiled twig template core/modules/help/templates/help-section.html.twig
 [success] Compiled twig template core/modules/image/templates/image-style.html.twig
 [success] Compiled twig template core/modules/image/templates/image-rotate-summary.html.twig
 [success] Compiled twig template core/modules/image/templates/image-scale-summary.html.twig
 [success] Compiled twig template core/modules/image/templates/image-formatter.html.twig
 [success] Compiled twig template core/modules/image/templates/image-crop-summary.html.twig
 [success] Compiled twig template core/modules/image/templates/image-anchor.html.twig
 [success] Compiled twig template core/modules/image/templates/image-resize-summary.html.twig
 [success] Compiled twig template core/modules/image/templates/image-style-preview.html.twig
 [success] Compiled twig template core/modules/image/templates/image-widget.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-resize-percentage-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-color-detail.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-set-canvas-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-text-overlay-preview.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-opacity-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-gaussian-blur-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-mask-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-set-transparent-color-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-imagemagick-arguments-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-convolution-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-watermark-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-mirror-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-background-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-interlace-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-convolution-sharpen-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-text-overlay-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-brightness-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-contrast-summary.html.twig
 [success] Compiled twig template modules/image_effects/templates/image-effects-color-shift-summary.html.twig
 [success] Compiled twig template modules/image_url_formatter/templates/image-url-formatter.html.twig
 [success] Compiled twig template core/modules/language/templates/language-negotiation-configure-form.html.twig
 [success] Compiled twig template core/modules/language/templates/language-content-settings-table.html.twig
 [success] Compiled twig template core/modules/link/templates/link-formatter-link-separate.html.twig
 [success] Compiled twig template core/modules/locale/templates/locale-translation-last-check.html.twig
 [success] Compiled twig template core/modules/locale/templates/locale-translation-update-info.html.twig
 [success] Compiled twig template core/modules/node/templates/field--node--created.html.twig
 [success] Compiled twig template core/modules/node/templates/field--node--uid.html.twig
 [success] Compiled twig template core/modules/node/templates/field--node--title.html.twig
 [success] Compiled twig template core/modules/node/templates/node-edit-form.html.twig
 [success] Compiled twig template core/modules/node/templates/node-add-list.html.twig
 [success] Compiled twig template core/modules/node/templates/node.html.twig
 [success] Compiled twig template core/modules/rdf/templates/rdf-wrapper.html.twig
 [success] Compiled twig template core/modules/rdf/templates/rdf-metadata.html.twig
 [success] Compiled twig template modules/recaptcha/templates/recaptcha-widget-noscript.html.twig
 [success] Compiled twig template core/modules/search/templates/search-result.html.twig
 [success] Compiled twig template modules/superfish/templates/superfish--help.html.twig
 [success] Compiled twig template modules/superfish/templates/superfish-menu-items.html.twig
 [success] Compiled twig template modules/superfish/templates/superfish.html.twig
 [success] Compiled twig template core/modules/system/templates/indentation.html.twig
 [success] Compiled twig template core/modules/system/templates/block--system-messages-block.html.twig
 [success] Compiled twig template core/modules/system/templates/radios.html.twig
 [success] Compiled twig template core/modules/system/templates/status-report.html.twig
 [success] Compiled twig template core/modules/system/templates/item-list.html.twig
 [success] Compiled twig template core/modules/system/templates/region.html.twig
 [success] Compiled twig template core/modules/system/templates/datetime-wrapper.html.twig
 [error]  Render context is empty, because render() was called outside of a renderRoot() or renderPlain() call. Use renderPlain()/renderRoot() or #lazy_builder/#pre_render instead.

```

Anything else I can provide to help?

**Comment by sriman** [comment] 2018-06-21 18:31
Me too faced the same issue while loading the view contents from **drush php-eval "php_method()"**

Solved it by

$view->execute();
$contents = \Drupal::service('renderer')->renderRoot($view->render());
